[playwright]
browsers = chromium
;headless = true
headless = false
timeout = 30000

[chromium]
launch_args = [
    "--disable-blink-features=AutomationControlled",
    "--disable-dev-shm-usage"
]

[firefox]
launch_args = []

[webkit]
launch_args = []